#!/bin/bash -e


function restore_saved_artifacts() {
  if [ "$(ls /tmp/artifacts/.gradle 2>/dev/null)" ]; then
    echo  "Restoring saved artifacts from prior build..."
    mv /tmp/artifacts/.gradle $HOME/.gradle
  fi
}

# Source code provided to S2I is at ${HOME}
if [[ "$1" == "-h" ]]; then
	exec /usr/libexec/s2i/usage
fi

export GRADLE_USER_HOME=${HOME}/.gradle

LOCAL_SOURCE_DIR=/tmp/src

DEPLOY_DIR=$CATALINA_HOME/webapps/

restore_saved_artifacts


pushd $LOCAL_SOURCE_DIR &> /dev/null

gradle :search:clean :search:build
gradle :client:clean :client:build
#gradle build distZip --info -exclude-task gitcall -exclude-task infofile

mkdir -p WEB-INF/lib
cp $CATALINA_HOME/modelfilter.jar WEB-INF/lib
zip ./search/build/libs/search.war WEB-INF/lib/modelfilter.jar

mv ./search/build/libs/search.war $DEPLOY_DIR
mv ./client/build/libs/client.war $DEPLOY_DIR
mv ./security-core/build/libs/security-core.jar $CATALINA_HOME/lib/

