#!/bin/bash -e
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#
#TODO only missing models
curl --head --silent --fail --location --max-time 16 $fedoraHost
function ingest2fedora {
  curl -vv -u "$fedoraUser:$fedoraPass" -H "Content-type:text/xml" -d "format=info:fedora/fedora-system:FOXML-1.1" -X POST --upload-file $1 $fedoraHost/objects/new
}

MODELS=/tmp/fedora/*.xml
for MODEL in $MODELS
do
  ingest2fedora $MODEL
done


exec $CATALINA_HOME/bin/catalina.sh run
