#!/bin/bash
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#
#TODO only missing models
function isFedoraUp {
count=0
while [ ${count} -lt 64 ]
echo "Wait for ${fedoraHost}"
do
  if curl --head --silent --fail --location --max-time 2 ${fedoraHost} > /dev/null; then
    echo "Fedora is running..."
    return 0
  fi
  sleep 1
  let count=${count}+1
done
return 1
}

function ingest2fedora {
  curl -vv -u "$fedoraUser:$fedoraPass" -H "Content-type:text/xml" -d "format=info:fedora/fedora-system:FOXML-1.1" -X POST --upload-file $1 $fedoraHost/objects/new
}


if isFedoraUp; then
  MODELS=/tmp/fedora/*.xml
  for MODEL in $MODELS
  do
      ingest2fedora $MODEL
  done
else 
  echo "model not ingested"
fi

exec $CATALINA_HOME/bin/catalina.sh run
